"""Add image file handling to all models

Revision ID: 397f1499c5a0
Revises: 
Create Date: 2024-05-22 11:36:21.688322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397f1499c5a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(length=16277215), nullable=True))
        batch_op.add_column(sa.Column('entry_fee', sa.String(), nullable=True))
        batch_op.drop_column('image_url')
        batch_op.drop_column('Entry_fee')

    with op.batch_alter_table('fun_times', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(length=16277215), nullable=True))
        batch_op.drop_column('image_url')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(length=16277215), nullable=True))
        batch_op.drop_column('image_url')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(length=16277215), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('image_data')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('image_data')

    with op.batch_alter_table('fun_times', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('image_data')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Entry_fee', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('entry_fee')
        batch_op.drop_column('image_data')

    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
